apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo
spec:
  selector:
    matchLabels:
      app: matomo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: matomo
    spec:
      containers:
      - image: bitnami/matomo:4.4.1
        name: matomo
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MATOMO_DATABASE_HOST
          value: [mariadb service]
        - name: MATOMO_DATABASE_NAME
          value: bitnami_matomo
        - name: MATOMO_DATABASE_PORT_NUMBER
          value: "3306"
        - name: MATOMO_DATABASE_USER
          value: root
        - name: MATOMO_DATABASE_PASSWORD
          value: [password]
        ports:
        - containerPort: 80
          name: matomo
        volumeMounts:
        - name: matomo-persistent-storage
          mountPath: /var/lib/matomo
      volumes:
      - name: matomo-persistent-storage
        persistentVolumeClaim:
          claimName: matomo-pv-claim
