apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default-storageclass
  annotations:
      storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: true
parameters:
  datastoreurl: ["datatore url"]
  fstype: ext4